/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface LogisticsRouteOptimizerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addPauser"
      | "finalizeRoute"
      | "getRouteRequest"
      | "getUserRoutes"
      | "markDeliveryCompleted"
      | "optimizedRoutes"
      | "owner"
      | "paused"
      | "pausers"
      | "processRouteOptimization"
      | "removePauser"
      | "requestRouteOptimization"
      | "routeCounter"
      | "routeLocations"
      | "routeRequests"
      | "togglePause"
      | "transferOwnership"
      | "userRoutes"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ContractPausedToggled"
      | "DeliveryCompleted"
      | "OwnershipTransferred"
      | "PauserAdded"
      | "PauserRemoved"
      | "RouteFinalized"
      | "RouteOptimized"
      | "RouteRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addPauser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeRoute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRouteRequest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserRoutes",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "markDeliveryCompleted",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "optimizedRoutes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pausers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "processRouteOptimization",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removePauser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestRouteOptimization",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "routeCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "routeLocations",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "routeRequests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "togglePause",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userRoutes",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addPauser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "finalizeRoute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRouteRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserRoutes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markDeliveryCompleted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "optimizedRoutes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pausers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processRouteOptimization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removePauser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestRouteOptimization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "routeCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "routeLocations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "routeRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "togglePause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userRoutes", data: BytesLike): Result;
}

export namespace ContractPausedToggledEvent {
  export type InputTuple = [paused: boolean];
  export type OutputTuple = [paused: boolean];
  export interface OutputObject {
    paused: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeliveryCompletedEvent {
  export type InputTuple = [
    routeId: BigNumberish,
    locationIndex: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    routeId: bigint,
    locationIndex: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    routeId: bigint;
    locationIndex: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PauserAddedEvent {
  export type InputTuple = [pauser: AddressLike];
  export type OutputTuple = [pauser: string];
  export interface OutputObject {
    pauser: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PauserRemovedEvent {
  export type InputTuple = [pauser: AddressLike];
  export type OutputTuple = [pauser: string];
  export interface OutputObject {
    pauser: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RouteFinalizedEvent {
  export type InputTuple = [
    routeId: BigNumberish,
    decryptedDistance: BigNumberish,
    decryptedTime: BigNumberish
  ];
  export type OutputTuple = [
    routeId: bigint,
    decryptedDistance: bigint,
    decryptedTime: bigint
  ];
  export interface OutputObject {
    routeId: bigint;
    decryptedDistance: bigint;
    decryptedTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RouteOptimizedEvent {
  export type InputTuple = [
    routeId: BigNumberish,
    requester: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    routeId: bigint,
    requester: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    routeId: bigint;
    requester: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RouteRequestedEvent {
  export type InputTuple = [
    routeId: BigNumberish,
    requester: AddressLike,
    locationCount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    routeId: bigint,
    requester: string,
    locationCount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    routeId: bigint;
    requester: string;
    locationCount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LogisticsRouteOptimizer extends BaseContract {
  connect(runner?: ContractRunner | null): LogisticsRouteOptimizer;
  waitForDeployment(): Promise<this>;

  interface: LogisticsRouteOptimizerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addPauser: TypedContractMethod<[_pauser: AddressLike], [void], "nonpayable">;

  finalizeRoute: TypedContractMethod<
    [routeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getRouteRequest: TypedContractMethod<
    [routeId: BigNumberish],
    [
      [string, bigint, boolean, bigint] & {
        requester: string;
        locationCount: bigint;
        processed: boolean;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getUserRoutes: TypedContractMethod<[user: AddressLike], [bigint[]], "view">;

  markDeliveryCompleted: TypedContractMethod<
    [routeId: BigNumberish, locationIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  optimizedRoutes: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, string, boolean, bigint, boolean] & {
        routeId: bigint;
        requester: string;
        totalDistance: string;
        totalDistanceSquared: string;
        estimatedTime: string;
        isConfidential: boolean;
        createdAt: bigint;
        finalized: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pausers: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  processRouteOptimization: TypedContractMethod<
    [routeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  removePauser: TypedContractMethod<
    [_pauser: AddressLike],
    [void],
    "nonpayable"
  >;

  requestRouteOptimization: TypedContractMethod<
    [
      xCoord: BigNumberish,
      yCoord: BigNumberish,
      priority: BigNumberish,
      maxDistance: BigNumberish,
      vehicleCapacityValue: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  routeCounter: TypedContractMethod<[], [bigint], "view">;

  routeLocations: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, string, string, boolean] & {
        encryptedX: string;
        encryptedY: string;
        priority: string;
        isActive: boolean;
      }
    ],
    "view"
  >;

  routeRequests: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string, boolean, bigint, bigint, bigint] & {
        requester: string;
        locationCount: bigint;
        maxTravelDistance: string;
        vehicleCapacity: string;
        processed: boolean;
        optimizedRouteId: bigint;
        timestamp: bigint;
        requestBlock: bigint;
      }
    ],
    "view"
  >;

  togglePause: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  userRoutes: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addPauser"
  ): TypedContractMethod<[_pauser: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "finalizeRoute"
  ): TypedContractMethod<[routeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getRouteRequest"
  ): TypedContractMethod<
    [routeId: BigNumberish],
    [
      [string, bigint, boolean, bigint] & {
        requester: string;
        locationCount: bigint;
        processed: boolean;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserRoutes"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "markDeliveryCompleted"
  ): TypedContractMethod<
    [routeId: BigNumberish, locationIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "optimizedRoutes"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, string, boolean, bigint, boolean] & {
        routeId: bigint;
        requester: string;
        totalDistance: string;
        totalDistanceSquared: string;
        estimatedTime: string;
        isConfidential: boolean;
        createdAt: bigint;
        finalized: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pausers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "processRouteOptimization"
  ): TypedContractMethod<[routeId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removePauser"
  ): TypedContractMethod<[_pauser: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestRouteOptimization"
  ): TypedContractMethod<
    [
      xCoord: BigNumberish,
      yCoord: BigNumberish,
      priority: BigNumberish,
      maxDistance: BigNumberish,
      vehicleCapacityValue: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "routeCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "routeLocations"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, string, string, boolean] & {
        encryptedX: string;
        encryptedY: string;
        priority: string;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "routeRequests"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string, boolean, bigint, bigint, bigint] & {
        requester: string;
        locationCount: bigint;
        maxTravelDistance: string;
        vehicleCapacity: string;
        processed: boolean;
        optimizedRouteId: bigint;
        timestamp: bigint;
        requestBlock: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "togglePause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userRoutes"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "ContractPausedToggled"
  ): TypedContractEvent<
    ContractPausedToggledEvent.InputTuple,
    ContractPausedToggledEvent.OutputTuple,
    ContractPausedToggledEvent.OutputObject
  >;
  getEvent(
    key: "DeliveryCompleted"
  ): TypedContractEvent<
    DeliveryCompletedEvent.InputTuple,
    DeliveryCompletedEvent.OutputTuple,
    DeliveryCompletedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PauserAdded"
  ): TypedContractEvent<
    PauserAddedEvent.InputTuple,
    PauserAddedEvent.OutputTuple,
    PauserAddedEvent.OutputObject
  >;
  getEvent(
    key: "PauserRemoved"
  ): TypedContractEvent<
    PauserRemovedEvent.InputTuple,
    PauserRemovedEvent.OutputTuple,
    PauserRemovedEvent.OutputObject
  >;
  getEvent(
    key: "RouteFinalized"
  ): TypedContractEvent<
    RouteFinalizedEvent.InputTuple,
    RouteFinalizedEvent.OutputTuple,
    RouteFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "RouteOptimized"
  ): TypedContractEvent<
    RouteOptimizedEvent.InputTuple,
    RouteOptimizedEvent.OutputTuple,
    RouteOptimizedEvent.OutputObject
  >;
  getEvent(
    key: "RouteRequested"
  ): TypedContractEvent<
    RouteRequestedEvent.InputTuple,
    RouteRequestedEvent.OutputTuple,
    RouteRequestedEvent.OutputObject
  >;

  filters: {
    "ContractPausedToggled(bool)": TypedContractEvent<
      ContractPausedToggledEvent.InputTuple,
      ContractPausedToggledEvent.OutputTuple,
      ContractPausedToggledEvent.OutputObject
    >;
    ContractPausedToggled: TypedContractEvent<
      ContractPausedToggledEvent.InputTuple,
      ContractPausedToggledEvent.OutputTuple,
      ContractPausedToggledEvent.OutputObject
    >;

    "DeliveryCompleted(uint32,uint8,uint256)": TypedContractEvent<
      DeliveryCompletedEvent.InputTuple,
      DeliveryCompletedEvent.OutputTuple,
      DeliveryCompletedEvent.OutputObject
    >;
    DeliveryCompleted: TypedContractEvent<
      DeliveryCompletedEvent.InputTuple,
      DeliveryCompletedEvent.OutputTuple,
      DeliveryCompletedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PauserAdded(address)": TypedContractEvent<
      PauserAddedEvent.InputTuple,
      PauserAddedEvent.OutputTuple,
      PauserAddedEvent.OutputObject
    >;
    PauserAdded: TypedContractEvent<
      PauserAddedEvent.InputTuple,
      PauserAddedEvent.OutputTuple,
      PauserAddedEvent.OutputObject
    >;

    "PauserRemoved(address)": TypedContractEvent<
      PauserRemovedEvent.InputTuple,
      PauserRemovedEvent.OutputTuple,
      PauserRemovedEvent.OutputObject
    >;
    PauserRemoved: TypedContractEvent<
      PauserRemovedEvent.InputTuple,
      PauserRemovedEvent.OutputTuple,
      PauserRemovedEvent.OutputObject
    >;

    "RouteFinalized(uint32,uint32,uint8)": TypedContractEvent<
      RouteFinalizedEvent.InputTuple,
      RouteFinalizedEvent.OutputTuple,
      RouteFinalizedEvent.OutputObject
    >;
    RouteFinalized: TypedContractEvent<
      RouteFinalizedEvent.InputTuple,
      RouteFinalizedEvent.OutputTuple,
      RouteFinalizedEvent.OutputObject
    >;

    "RouteOptimized(uint32,address,uint256)": TypedContractEvent<
      RouteOptimizedEvent.InputTuple,
      RouteOptimizedEvent.OutputTuple,
      RouteOptimizedEvent.OutputObject
    >;
    RouteOptimized: TypedContractEvent<
      RouteOptimizedEvent.InputTuple,
      RouteOptimizedEvent.OutputTuple,
      RouteOptimizedEvent.OutputObject
    >;

    "RouteRequested(uint32,address,uint32,uint256)": TypedContractEvent<
      RouteRequestedEvent.InputTuple,
      RouteRequestedEvent.OutputTuple,
      RouteRequestedEvent.OutputObject
    >;
    RouteRequested: TypedContractEvent<
      RouteRequestedEvent.InputTuple,
      RouteRequestedEvent.OutputTuple,
      RouteRequestedEvent.OutputObject
    >;
  };
}
